# Generated by Django 5.1.6 on 2025-02-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=200)),
                ("recom_rec_name", models.CharField(max_length=255)),
                ("list", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rec_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rec_img",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
