# Generated by Django 5.1.6 on 2025-02-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userlist_alter_recipe_rec_id_alter_recipe_rec_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
